on: [push]

jobs:
  run_automation:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Execute tests
          uses: tarathep/robotframework-github-action@v1.0
          with:
           tests_dir: '${{ github.workspace }}/tests/robot'
           reports_dir: '${{ github.workspace }}/tests/robot/reports'

